# Generated by Django 3.2.4 on 2021-06-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreras',
            name='len_circuito',
        ),
        migrations.RemoveField(
            model_name='carreras',
            name='vueltas',
        ),
    ]
